apiVersion: v1
kind: Service
metadata:
  name: pagamentos
  namespace: pedidos-veloz
  labels:
    app: pagamentos
spec:
  type: ClusterIP
  selector:
    app: pagamentos
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
